project:
  type: website
  output-dir: docs
  preview:
    port: 4200
    browser: false

website:
  title: "Terminus"
  description: "An adaptive science fiction universe that evolves with real-world space developments"
  site-url: https://hariseldon23.github.io/terminus
  repo-url: https://github.com/HariSeldon23/terminus
  repo-actions: [edit, issue]
  
  page-navigation: true
  
  sidebar:
    style: "floating"
    search: true
    tools:
      - icon: github
        href: https://github.com/HariSeldon23/terminus
    contents:
      - section: "Universe Overview"
        contents:
          - href: index.qmd
            text: "Home"
      - section: "Timeline"
        contents:
          - href: timeline/main.qmd
            text: "Current Timeline"
      - section: "Core Universe"
        contents:
          - href: core/anchor-points.qmd
            text: "Anchor Points Index"
          - href: core/societies.qmd
            text: "The Major Societies"
          - href: core/law.qmd
            text: "Space Law and Regulation"
          - href: core/stations.qmd
            text: "Space Stations"
          - href: core/technology/technology.qmd
            text: "Technology"
          - href: core/locations/moon-base.qmd
            text: "Lunar Operations Base"
                
      - section: "Characters"
        contents:
          - href: characters/index.qmd
            text: "Character Directory"
      
      - section: "Stories"
        contents:
          - href: stories/first.qmd
            text: "Into the Void"
          - href: stories/second.qmd
            text: "Second"
          - href: stories/third.qmd
            text: "Third"
      - section: "Contributing"
        contents:
          - href: creators/guide.qmd
            text: "Creating in Terminus"
          - href: creators/storytelling.qmd
            text: "Storytelling"
          - href: creators/style-guide.qmd
            text: "Style Guide"

  page-footer:
    left: "Copyright 2025 Terminus Universe"
    right:
      - icon: github
        href: https://github.com/yourusername/terminus

format:
  html:
    theme:
      light: cosmo
      dark: darkly
    mainfont: "Source Sans Pro"
    monofont: "Fira Code"
    code-copy: true
    code-overflow: wrap
    toc: true
    toc-location: right
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    
metadata-files:
  - _variables.yml
  - _metadata.yml

execute:
  freeze: auto

bibliography: references.bib